# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: html_data.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='html_data.proto',
  package='proto',
  serialized_pb='\n\x0fhtml_data.proto\x12\x05proto\"\xea\x01\n\x0cNewsHtmlData\x12\x1e\n\thint_type\x18\x01 \x02(\x0e\x32\x0b.proto.Type\x12\r\n\x05title\x18\x02 \x01(\t\x12\x12\n\nshare_icon\x18\x03 \x01(\t\x12\x11\n\tpublished\x18\x04 \x01(\t\x12\x12\n\nsource_url\x18\x05 \x01(\t\x12\x10\n\x08subtitle\x18\x06 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x07 \x01(\t\x12\x11\n\tthumbnail\x18\x08 \x01(\t\x12\x12\n\nvideo_type\x18\t \x01(\t\x12\x12\n\ntarget_url\x18\n \x01(\t\x12\x12\n\nimage_zoom\x18\x0b \x01(\t*M\n\x04Type\x12\x0b\n\x07\x61rticle\x10\x01\x12\t\n\x05\x61lbum\x10\x02\x12\t\n\x05video\x10\x03\x12\x10\n\x0ctencent_open\x10\x04\x12\x10\n\x0chref_article\x10\x05\x42%\n\x15\x63om.cootek.data.protoB\x0cHtmlDataType')

_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='proto.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='article', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='album', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='video', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='tencent_open', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='href_article', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=263,
  serialized_end=340,
)

Type = enum_type_wrapper.EnumTypeWrapper(_TYPE)
article = 1
album = 2
video = 3
tencent_open = 4
href_article = 5



_NEWSHTMLDATA = _descriptor.Descriptor(
  name='NewsHtmlData',
  full_name='proto.NewsHtmlData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hint_type', full_name='proto.NewsHtmlData.hint_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='proto.NewsHtmlData.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='share_icon', full_name='proto.NewsHtmlData.share_icon', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='published', full_name='proto.NewsHtmlData.published', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source_url', full_name='proto.NewsHtmlData.source_url', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subtitle', full_name='proto.NewsHtmlData.subtitle', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='proto.NewsHtmlData.content', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='thumbnail', full_name='proto.NewsHtmlData.thumbnail', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='video_type', full_name='proto.NewsHtmlData.video_type', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_url', full_name='proto.NewsHtmlData.target_url', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_zoom', full_name='proto.NewsHtmlData.image_zoom', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=261,
)

_NEWSHTMLDATA.fields_by_name['hint_type'].enum_type = _TYPE
DESCRIPTOR.message_types_by_name['NewsHtmlData'] = _NEWSHTMLDATA

class NewsHtmlData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NEWSHTMLDATA

  # @@protoc_insertion_point(class_scope:proto.NewsHtmlData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\025com.cootek.data.protoB\014HtmlDataType')
# @@protoc_insertion_point(module_scope)
